version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employees"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7

    container_name: redis-cache

    ports:
      - "6379:6379"

  employee-api:

    build: .

    container_name: employee-api

    ports:
      - "5000:5000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/employees
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:

  postgres_data:
